name: Marking pull requests as stale and closing them

on:
  workflow_dispatch:
    inputs:
      debug-only:
        description: 'Do you want to run the workflow in debug mode?'
        default: true
        required: true
  schedule:
  - cron: "30 1 * * *"


jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        stale-pr-message: 'This PR is stale because it has been open for 60 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
        close-pr-message: 'This PR is being closed because it has been stale for 7 days with no activity.'
        debug-only: ${{ github.event.inputs.debug-only || true }}
